name : "Testeto App"

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio 
        uses: actions/checkout@v3

      - name: Instalar PHP en mi ambiente
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Instalar Composer
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Crear archivo .env
        run: |
          cp .env.example .env

      - name: Generar una llave
        run: php artisan key:generate

      - name: Correr migraciones
        run: php artisan migrate --env=testing